services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: recruitment
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init_schema.sql:/docker-entrypoint-initdb.d/01_init.sql

volumes:
  pgdata:
